[package]
name = "project_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
colored = "2.1.0"
serde_json = "1.0.108"
crossterm = "0.27.0"
base64 = "0.21.6"